import{FLEET,createBoard,placeShip,autoPlace,shoot,allSunk,randomShot}from"./game.js";const $=id=>document.getElementById(id),KEY="pg-seabattle-best";let mine,enemy,placing,vertical,phase,shots,best=Number(localStorage.getItem(KEY)||0);
function reset(){mine=createBoard();enemy=createBoard();autoPlace(enemy);placing=0;vertical=false;phase="place";shots=0;$("status").textContent="點選我方海域放置船艦";render()}
function cell(board,i,reveal,click){const b=document.createElement("button");b.className="cell";const ship=board.cells[i],shot=board.shots[i];if(reveal&&ship)b.classList.add("ship");if(shot)b.classList.add(ship?"hit":"miss");b.setAttribute("aria-label",`${Math.floor(i/10)+1} 列 ${i%10+1} 欄`);b.onclick=()=>click(i);return b}
function renderGrid(el,b,reveal,click){el.innerHTML="";for(let i=0;i<100;i++)el.append(cell(b,i,reveal,click))}
function render(){renderGrid($("mine"),mine,true,place);renderGrid($("enemy"),enemy,false,fire);$("placing").textContent=phase==="place"?`待放：${FLEET[placing]||0} 格船艦`:"艦隊已就位，請砲擊敵方海域";$("score").textContent=shots;$("extra").textContent=phase==="place"?"佈艦階段":"交戰中";$("best").textContent=best;$("auto").disabled=phase!=="place";$("rotate").disabled=phase!=="place"}
function place(i){if(phase!=="place")return;const ok=placeShip(mine,Math.floor(i/10),i%10,FLEET[placing],vertical);if(!ok)return $("status").textContent="此處無法放置，請換位置";placing++;if(placing===FLEET.length){phase="battle";$("status").textContent="佈艦完成，請攻擊敵方"}render()}
function computer(){const p=randomShot(mine);if(!p)return;const r=shoot(mine,p.r,p.c);$("status").textContent+=r.result==="miss"?"；敵軍未命中":"；敵軍命中我方！";if(allSunk(mine)){phase="over";$("status").textContent="我方艦隊全數沉沒"}render()}
async function win(){phase="over";const score=Math.max(1,101-shots);$("status").textContent=`勝利！共發射 ${shots} 砲`;if(score>best){best=score;localStorage.setItem(KEY,best);try{await fetch("/api/kv/"+KEY,{method:"PUT",body:String(best)})}catch{}}render()}
function fire(i){if(phase!=="battle")return;const r=shoot(enemy,Math.floor(i/10),i%10);if(r.result==="repeat")return;shots++;$("status").textContent=r.result==="miss"?"未命中":r.result==="sunk"?"擊沉敵艦！":"命中！";if(allSunk(enemy))return win();computer()}
$("rotate").onclick=()=>{vertical=!vertical;$("rotate").textContent=`方向：${vertical?"直向":"橫向"}`};$("auto").onclick=()=>{mine=createBoard();autoPlace(mine);placing=FLEET.length;phase="battle";$("status").textContent="自動佈艦完成，請攻擊敵方";render()};$("new").onclick=reset;/* Future Invite 1v1: replace local AI turn with signed remote shot events. */(async()=>{try{const r=await fetch("/api/kv/"+KEY),n=Number(await r.text());if(r.ok&&Number.isFinite(n))best=Math.max(best,n)}catch{}reset()})();